import type { Finding, ScanResult, Severity } from '../types.js';

const SEVERITY_COLORS: Record<Severity, string> = {
  critical: '#dc2626',
  high: '#ea580c',
  medium: '#ca8a04',
  low: '#2563eb',
  info: '#6b7280',
};

const SEVERITY_BG: Record<Severity, string> = {
  critical: '#fef2f2',
  high: '#fff7ed',
  medium: '#fefce8',
  low: '#eff6ff',
  info: '#f9fafb',
};

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function findingCard(finding: Finding): string {
  const color = SEVERITY_COLORS[finding.severity];
  const bg = SEVERITY_BG[finding.severity];
  return `
    <div style="border-left:4px solid ${color};background:${bg};padding:16px;margin-bottom:12px;border-radius:0 8px 8px 0;">
      <div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;">
        <span style="background:${color};color:white;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:600;text-transform:uppercase;">${escapeHtml(finding.severity)}</span>
        <strong style="font-size:15px;">${escapeHtml(finding.title)}</strong>
      </div>
      <div style="color:#374151;font-size:14px;margin-bottom:8px;">${escapeHtml(finding.description)}</div>
      <div style="font-size:13px;color:#6b7280;">
        <span>Rule: <code>${escapeHtml(finding.ruleId)}</code></span>
        &nbsp;|&nbsp;
        <span>File: <code>${escapeHtml(finding.filePath)}${finding.line ? `:${finding.line}` : ''}</code></span>
      </div>
      ${finding.evidence ? `<div style="margin-top:8px;font-size:13px;"><strong>Evidence:</strong> <code>${escapeHtml(finding.evidence)}</code></div>` : ''}
      <div style="margin-top:8px;font-size:13px;color:#047857;"><strong>Fix:</strong> ${escapeHtml(finding.recommendation)}</div>
    </div>`;
}

function summaryBadge(severity: Severity, count: number): string {
  if (count === 0) return '';
  const color = SEVERITY_COLORS[severity];
  return `<span style="background:${color};color:white;padding:4px 12px;border-radius:16px;font-size:14px;font-weight:600;">${count} ${severity.toUpperCase()}</span>`;
}

export function formatHtml(result: ScanResult): string {
  const counts: Record<Severity, number> = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
  for (const f of result.findings) counts[f.severity]++;

  const badges = (['critical', 'high', 'medium', 'low', 'info'] as Severity[])
    .map((s) => summaryBadge(s, counts[s]))
    .filter(Boolean)
    .join(' ');

  const noIssues = result.findings.length === 0;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MCP Fortify Security Report</title>
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; background:#f8fafc; color:#1e293b; padding:32px; max-width:900px; margin:0 auto; }
    code { background:#e2e8f0; padding:2px 6px; border-radius:4px; font-size:13px; }
    h1 { font-size:24px; margin-bottom:4px; }
    .meta { color:#64748b; font-size:14px; margin-bottom:24px; }
    .summary { display:flex; gap:8px; flex-wrap:wrap; margin-bottom:24px; }
    .pass { background:#dcfce7; color:#166534; padding:16px; border-radius:8px; font-size:16px; font-weight:600; text-align:center; }
    .files { margin-top:24px; padding:16px; background:#f1f5f9; border-radius:8px; }
    .files summary { cursor:pointer; font-weight:600; font-size:14px; color:#475569; }
    .files ul { margin-top:8px; padding-left:20px; font-size:13px; color:#64748b; }
    .footer { margin-top:32px; text-align:center; color:#94a3b8; font-size:12px; }
  </style>
</head>
<body>
  <h1>MCP Fortify Security Report</h1>
  <div class="meta">Scanned ${result.scannedFiles.length} files in ${result.duration.toFixed(0)}ms &mdash; ${new Date(result.timestamp).toLocaleString()}</div>

  ${noIssues
    ? '<div class="pass">No security issues found!</div>'
    : `<div class="summary">${badges}</div>${result.findings.map(findingCard).join('')}`
  }

  <details class="files">
    <summary>Scanned Files (${result.scannedFiles.length})</summary>
    <ul>${result.scannedFiles.map((f) => `<li>${escapeHtml(f)}</li>`).join('')}</ul>
  </details>

  <div class="footer">Generated by <a href="https://github.com/SSMMSS884/mcp-fortify" style="color:#64748b;">mcp-fortify</a></div>
</body>
</html>`;
}
