import { existsSync, mkdirSync, writeFileSync, chmodSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import chalk from 'chalk';

const HOOK_SCRIPT = `#!/bin/bash
# MCP Fortify: Block file writes containing secrets/credentials
# Generated by: mcp-fortify init

INPUT=$(cat)

CONTENT=$(echo "$INPUT" | jq -r '
  .tool_input.content //
  .tool_input.new_string //
  empty
')

if [ -z "$CONTENT" ]; then
  exit 0
fi

# Secret patterns
if echo "$CONTENT" | grep -qE '(sk-[a-zA-Z0-9_-]{20,}|AKIA[0-9A-Z]{16}|ghp_[a-zA-Z0-9]{36}|gho_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9_]{20,}|AIza[0-9A-Za-z_-]{35}|xox[bpras]-[0-9a-zA-Z]{10,}|npm_[a-zA-Z0-9]{36}|SG\\.[a-zA-Z0-9_-]{22}\\.[a-zA-Z0-9_-]{43})'; then
  FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // "unknown"')
  echo "BLOCKED: Secret pattern detected in write to $FILE_PATH" >&2
  echo "Use macOS Keychain: secrets store KEY_NAME \\"value\\"" >&2
  exit 2
fi

# Generic credential patterns (with placeholder exclusion)
if echo "$CONTENT" | grep -qE '(API_KEY|SECRET|TOKEN|PASSWORD)\\s*[=:]\\s*[a-zA-Z0-9_.+/-]{20,}'; then
  if ! echo "$CONTENT" | grep -qE '(YOUR_|REPLACE_|xxx|placeholder|example|changeme)'; then
    FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // "unknown"')
    echo "WARNING: Possible credential in write to $FILE_PATH" >&2
    exit 2
  fi
fi

exit 0
`;

export function runInit(): void {
  const home = homedir();
  const hooksDir = join(home, '.claude', 'hooks');
  const hookPath = join(hooksDir, 'mcp-fortify-block-secrets.sh');
  const settingsPath = join(home, '.claude', 'settings.json');

  console.log('');
  console.log(chalk.bold('  MCP Fortify — Init'));
  console.log('');

  // 1. Create hooks directory if needed
  if (!existsSync(hooksDir)) {
    mkdirSync(hooksDir, { recursive: true });
    console.log(chalk.green('  + Created hooks directory: ') + hooksDir);
  }

  // 2. Write hook script
  if (existsSync(hookPath)) {
    console.log(chalk.yellow('  ~ Hook already exists: ') + hookPath);
  } else {
    writeFileSync(hookPath, HOOK_SCRIPT, { mode: 0o700 });
    console.log(chalk.green('  + Created secret-blocking hook: ') + hookPath);
  }

  // 3. Add hook to settings.json
  let settings: Record<string, unknown> = {};
  if (existsSync(settingsPath)) {
    try {
      const raw = require('fs').readFileSync(settingsPath, 'utf-8');
      settings = JSON.parse(raw);
    } catch {
      // start fresh
    }
  }

  if (!settings.hooks) settings.hooks = {};
  const hooks = settings.hooks as Record<string, unknown[]>;

  if (!hooks.PreToolUse) hooks.PreToolUse = [];
  const preToolUse = hooks.PreToolUse as Array<Record<string, unknown>>;

  // Check if our hook is already registered
  const alreadyRegistered = preToolUse.some((group) => {
    if (typeof group.command === 'string' && group.command.includes('mcp-fortify')) return true;
    if (Array.isArray(group.hooks)) {
      return group.hooks.some(
        (h: unknown) =>
          typeof h === 'object' && h !== null &&
          typeof (h as Record<string, unknown>).command === 'string' &&
          ((h as Record<string, unknown>).command as string).includes('mcp-fortify'),
      );
    }
    return false;
  });

  if (alreadyRegistered) {
    console.log(chalk.yellow('  ~ Hook already registered in settings.json'));
  } else {
    preToolUse.push({
      matcher: 'Write|Edit',
      hooks: [
        {
          type: 'command',
          command: hookPath,
          timeout: 10,
        },
      ],
    });

    writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
    chmodSync(settingsPath, 0o600);
    console.log(chalk.green('  + Registered hook in: ') + settingsPath);
  }

  console.log('');
  console.log(chalk.green.bold('  Done!') + ' Your MCP setup now blocks secret writes.');
  console.log(chalk.gray('  Run `mcp-fortify scan` to verify.'));
  console.log('');
}
